version: "3.8"

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
    command: --bind-address=0.0.0.0
    volumes:
      - mariadb_data:/var/lib/mysql

  orthanc:
    image: jodogne/orthanc
    container_name: orthanc
    restart: unless-stopped
    ports:
      - "8042:8042"
      - "4242:4242"
    volumes:
      - ./orthanc/orthanc.json:/etc/orthanc/orthanc.json
      - orthanc_data:/var/lib/orthanc/db

volumes:
  mariadb_data:
  orthanc_data:
